name: Production
on:
  push:
    branches:
      - main
jobs:
  unit_test: 
    name: Run unit tests
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i && cd client && npm i
      - name: Run test script
        run: npm test
  deploy:
    name: Deploy to S3
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clean install dependencies
        run: npm ci && cd client && npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
