name: Production Deploy
on:
  push:
    tags:
      - "release-v[0-9]+.[0-9]+.[0-9]+"
jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clean install dependencies
        run: npm ci
      - name: Deploy
        run: npm run deploy:prod
        env:
          DOTENV_PRIVATE_KEY_PROD: ${{ secrets.DOTENV_PRIVATE_KEY_PROD }}
